=== manami-project/manami/manami-app/src/test/resources/fileimport/parser/manami/LegacyManamiParser/animelist.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT manami (animeList, watchList, filterList)>
<!ATTLIST manami version CDATA #REQUIRED>

<!ELEMENT animeList (anime*)>
<!ELEMENT anime EMPTY>
<!ATTLIST anime episodes CDATA #REQUIRED
infoLink CDATA #IMPLIED
location CDATA #REQUIRED
title CDATA #REQUIRED
type CDATA #REQUIRED>

<!ELEMENT watchList (watchListEntry*)>
<!ELEMENT watchListEntry EMPTY>
<!ATTLIST watchListEntry infoLink CDATA #REQUIRED
thumbnail CDATA #REQUIRED
title CDATA #REQUIRED>

<!ELEMENT filterList (filterEntry*)>
<!ELEMENT filterEntry EMPTY>
<!ATTLIST filterEntry infoLink CDATA #REQUIRED
thumbnail CDATA #REQUIRED
title CDATA #REQUIRED>

=== manami-project/manami/manami-app/src/test/resources/fileimport/parser/manami/LegacyManamiParser/correctly_parse_entries.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xml" href="animelist_transform.xsl"?>
<!DOCTYPE manami SYSTEM "animelist.dtd">
<manami version="2.17.6">
  <animeList>
    <anime episodes="26" infoLink="https://myanimelist.net/anime/57" location="some/relative/path/beck" title="Beck" type="TV"/>
    <anime episodes="4" infoLink="" location="some/relative/path/h2o_-_footprints_in_the_sand_special" title="H2O: Footprints in the Sand" type="Special"/>
  </animeList>
  <watchList>
    <watchListEntry infoLink="https://myanimelist.net/anime/37989" thumbnail="https://cdn.myanimelist.net/images/anime/1180/95018t.jpg" title="Golden Kamuy 2nd Season"/>
    <watchListEntry infoLink="https://myanimelist.net/anime/40059" thumbnail="https://cdn.myanimelist.net/images/anime/1510/101944t.jpg" title="Golden Kamuy 3rd Season"/>
  </watchList>
  <filterList>
    <filterEntry infoLink="https://myanimelist.net/anime/28981" thumbnail="https://cdn.myanimelist.net/images/anime/10/72517t.jpg" title="Ame-iro Cocoa"/>
    <filterEntry infoLink="https://myanimelist.net/anime/33245" thumbnail="https://cdn.myanimelist.net/images/anime/3/82186t.jpg" title="Ame-iro Cocoa in Hawaii"/>
    <filterEntry infoLink="https://myanimelist.net/anime/35923" thumbnail="https://cdn.myanimelist.net/images/anime/3/88225t.jpg" title="Ame-iro Cocoa Series: Ame-con!!"/>
    <filterEntry infoLink="https://myanimelist.net/anime/31139" thumbnail="https://cdn.myanimelist.net/images/anime/10/76340t.jpg" title="Ame-iro Cocoa: Rainy Color e Youkoso!"/>
    <filterEntry infoLink="https://myanimelist.net/anime/37747" thumbnail="https://cdn.myanimelist.net/images/anime/1463/97361t.jpg" title="Ame-iro Cocoa: Side G"/>
  </filterList>
</manami>
