=== manami-project/manami/manami-app/src/test/resources/file/FileParser/animelist.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT manami (animeList, watchList, ignoreList)>
<!ATTLIST manami version CDATA #REQUIRED>

<!ELEMENT animeList (animeListEntry*)>
<!ELEMENT animeListEntry EMPTY>
<!ATTLIST animeListEntry episodes CDATA #REQUIRED
    link CDATA #IMPLIED
    title CDATA #REQUIRED
    thumbnail CDATA #REQUIRED
    type CDATA #REQUIRED
    episodes CDATA #REQUIRED
    location CDATA #REQUIRED
>

<!ELEMENT watchList (watchListEntry*)>
<!ELEMENT watchListEntry EMPTY>
<!ATTLIST watchListEntry episodes CDATA #REQUIRED
    link CDATA #REQUIRED
    title CDATA #REQUIRED
    thumbnail CDATA #REQUIRED
>

<!ELEMENT ignoreList (ignoreListEntry*)>
<!ELEMENT ignoreListEntry EMPTY>
<!ATTLIST ignoreListEntry episodes CDATA #REQUIRED
    link CDATA #REQUIRED
    title CDATA #REQUIRED
    thumbnail CDATA #REQUIRED
>

=== manami-project/manami/manami-app/src/test/resources/file/FileParser/correctly_parse_entries.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/xml" href="animelist_transform.xsl"?><!DOCTYPE manami SYSTEM "src/test/resources/file/FileParser/animelist.dtd">
<manami version="3.0.0">
  <animeList>
    <animeListEntry link="https://myanimelist.net/anime/57" title="Beck" thumbnail="https://cdn.myanimelist.net/images/anime/11/11636t.jpg" type="TV" episodes="26" location="some/relative/path/beck"/>
    <animeListEntry link="" title="H2O: Footprints in the Sand" thumbnail="https://cdn.myanimelist.net/images/qm_50.gif" type="SPECIAL" episodes="4" location="some/relative/path/h2o_-_footprints_in_the_sand_special"/>
  </animeList>
  <watchList>
    <watchListEntry link="https://myanimelist.net/anime/37989" title="Golden Kamuy 2nd Season" thumbnail="https://cdn.myanimelist.net/images/anime/1180/95018t.jpg"/>
    <watchListEntry link="https://myanimelist.net/anime/40059" title="Golden Kamuy 3rd Season" thumbnail="https://cdn.myanimelist.net/images/anime/1763/108108t.jpg"/>
  </watchList>
  <ignoreList>
    <ignoreListEntry link="https://myanimelist.net/anime/28981" title="Ame-iro Cocoa" thumbnail="https://cdn.myanimelist.net/images/anime/1957/111714t.jpg"/>
    <ignoreListEntry link="https://myanimelist.net/anime/33245" title="Ame-iro Cocoa in Hawaii" thumbnail="https://cdn.myanimelist.net/images/anime/1727/111715t.jpg"/>
    <ignoreListEntry link="https://myanimelist.net/anime/35923" title="Ame-iro Cocoa Series: Ame-con!!" thumbnail="https://cdn.myanimelist.net/images/anime/1165/111716t.jpg"/>
    <ignoreListEntry link="https://myanimelist.net/anime/31139" title="Ame-iro Cocoa: Rainy Color e Youkoso!" thumbnail="https://cdn.myanimelist.net/images/anime/1065/111717t.jpg"/>
    <ignoreListEntry link="https://myanimelist.net/anime/37747" title="Ame-iro Cocoa: Side G" thumbnail="https://cdn.myanimelist.net/images/anime/1394/111379t.jpg"/>
  </ignoreList>
</manami>
